services:
  audio-processor:
    command: poetry run python -m watchfiles coalesce_audio_processor.worker.http.main
    volumes:
      - ./audio-processor:/app

  app:
    command: npm start -- --port 3000 --host
    volumes:
      - ./app:/app/frontend
      - ./shared:/app/shared

  api-server:
    command: task api:dev
    volumes:
      - ./project-server:/app/project-server
      - ./shared:/app/shared
    environment:
      - COALESCE_DEV_FLAGS=reuse-track-by-filename

  collab-server:
    command: task collab:dev
    volumes:
      - ./project-server:/app/project-server
      - ./shared:/app/shared

  minio-client:
    profiles: ['tools']
    image: quay.io/minio/mc
    entrypoint: >
      sh -c 'mc alias set minio http://minio:9000 "$$MINIO_ROOT_USER" "$$MINIO_ROOT_PASSWORD" && bash'
    depends_on:
      - minio
    env_file:
      - docker-compose.env

  site:
    command: npm start -- --port 4321 --host
    volumes:
      - ./site:/app/site
      - ./shared:/app/shared
