services:
  redis:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redis:/data

  minio:
    image: quay.io/minio/minio
    command: server /data
    volumes:
      - minio:/data
    ports:
      - '9000:9000'
    env_file:
      - docker-compose.env

  audio-processor:
    profiles: ['cpu']
    image: coalesce/audio-processor
    build:
      context: ./audio-processor
      dockerfile: ./Dockerfile
    depends_on:
      - redis
      - minio
    env_file:
      - docker-compose.env

  audio-processor-gpu:
    profiles: ['gpu']
    image: coalesce/audio-processor
    build:
      context: ./audio-processor
      dockerfile: ./Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - redis
      - minio
    env_file:
      - docker-compose.env

  app:
    image: coalesce/app
    build:
      context: .
      dockerfile: ./app/Dockerfile
      args:
        - VITE_PROJECT_SERVER=${VITE_PROJECT_SERVER:-localhost:3001}
    ports:
      - '3000:3000'
    environment:
      - VITE_PROJECT_SERVER=${VITE_PROJECT_SERVER:-localhost:3001}

  project-server:
    image: coalesce/project-server
    build:
      context: .
      dockerfile: ./project-server/Dockerfile
    depends_on:
      - redis
      - minio
    ports:
      - '3001:3001'
    env_file:
      - docker-compose.env
    environment:
      - APP_ORIGIN=${APP_ORIGIN:-http://localhost:3000}

volumes:
  minio:
  redis:
