services:
  redis:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redis:/data

  audio-processor:
    image: coalesce/audio-processor
    build:
      context: ./audio-processor
      dockerfile: ./Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - redis
    volumes:
      - data:/data
    env_file:
      - docker-compose.env

  app:
    image: coalesce/app
    build:
      context: .
      dockerfile: ./app/Dockerfile
      args:
        - VITE_PROJECT_SERVER=${VITE_PROJECT_SERVER:-localhost:3001}
    ports:
      - '3000:3000'
    environment:
      - VITE_PROJECT_SERVER=${VITE_PROJECT_SERVER:-localhost:3001}

  project-server:
    image: coalesce/project-server
    build:
      context: .
      dockerfile: ./project-server/Dockerfile
    depends_on:
      - redis
    ports:
      - '3001:3001'
    volumes:
      - data:/data
    env_file:
      - docker-compose.env
    environment:
      - APP_ORIGIN=${APP_ORIGIN:-http://localhost:3000}

volumes:
  data:
  redis:
