services:
  app:
    command: npm start -- --port 3000 --host --base /
    volumes:
      - ./app:/app/frontend
      - ./shared:/app/shared
    ports:
      - '3000:3000'
    environment:
      - VITE_CHUNK_GET_CREDENTIALS=include
