services:
  audio-processor:
    command: poetry run python -m watchfiles coalesce_audio_processor.worker.http.main
    volumes:
      - ./audio-processor:/app

  app:
    command: npm start -- --port 3000 --host
    volumes:
      - ./app:/app/frontend
      - ./shared:/app/shared

  project-server:
    command: run --watch --allow-net --allow-env --allow-read=/app/project-server/,/usr/bin/deno main.ts
    volumes:
      - ./project-server:/app/project-server
      - ./shared:/app/shared
    environment:
      - COALESCE_DEV_FLAGS=reuse-track-by-filename

  minio-client:
    profiles: ['tools']
    image: quay.io/minio/mc
    entrypoint: >
      sh -c 'mc alias set minio http://minio:9000 "$$MINIO_ROOT_USER" "$$MINIO_ROOT_PASSWORD" && bash'
    depends_on:
      - minio
    env_file:
      - docker-compose.env
