apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coalesce-audio-processor.fullname" . }}
  labels:
    {{- include "coalesce-audio-processor.labels" . | nindent 4 }}
type: Opaque
data:
  workerKey: {{ .Values.workerKey | b64enc | quote }}
