apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coalesce-collab-server.fullname" . }}
  labels:
    {{- include "coalesce-collab-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "coalesce-collab-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "coalesce-collab-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["deno", "run", "--allow-net", "--allow-env", "--allow-read=/app/project-server/,/usr/bin/deno", "collab/main.ts"]
          ports:
            - name: http
              containerPort: {{ .Values.servePort }}
              protocol: TCP
          env:
            - name: COLLAB_SERVER_PORT
              value: {{ .Values.servePort | toString | quote }}
            - name: COLLAB_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_URL
              value: {{ .Values.redisURL }}
            - name: POSTGRES_URL
              value: {{ .Values.postgresURL }}
            - name: MINIO_ENDPOINT
              value: {{ .Values.minioEndpoint }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}