apiVersion: v1
kind: Service
metadata:
  name: {{ include "coalesce-collab-server.fullname" . }}
  labels: {{- include "coalesce-collab-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "coalesce-collab-server.selectorLabels" . | nindent 4 }}
