apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coalesce-api-server.fullname" . }}
  labels:
    {{- include "coalesce-api-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "coalesce-api-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "coalesce-api-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["deno", "run", "--allow-net", "--allow-env", "--allow-read=/app/project-server/,/usr/bin/deno", "api/main.ts"]
          ports:
            - name: http
              containerPort: {{ .Values.servePort }}
              protocol: TCP
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "coalesce-api-server.fullname" . }}
                  key: redisURL
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "coalesce-api-server.fullname" . }}
                  key: postgresURL
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ include "coalesce-api-server.fullname" . }}
                  key: minioEndpoint
            - name: PROJECT_SERVER_PORT
              value: {{ .Values.servePort | toString | quote }}
            - name: APP_ORIGIN
              value: {{ .Values.urls.appOrigin }}
            - name: COLLAB_ENDPOINT
              value: {{ .Values.endpoints.collab }}
            - name: KRATOS_URL
              value: {{ .Values.endpoints.kratos.public }}
            - name: KRATOS_ADMIN_URL
              value: {{ .Values.endpoints.kratos.admin }}
            - name: WORKER_PROXY_ORIGIN
              value: {{ .Values.endpoints.worker.proxyOrigin }}
            - name: WORKER_ENDPOINT
              value: {{ .Values.endpoints.worker.job }}
            - name: AUDIO_QUEUE_NAME
              value: {{ .Values.queues.audio.inbox }}
            - name: AUDIO_PROCESSING_QUEUE_NAME
              value: {{ .Values.queues.audio.processing }}
            - name: WORKER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "coalesce-api-server.fullname" . }}
                  key: workerKey
            - name: TRACK_CDN_HOST
              value: {{ .Values.urls.trackCDNHost }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.servePort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.servePort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}