apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coalesce-api-server.fullname" . }}
  labels:
    {{- include "coalesce-api-server.labels" . | nindent 4 }}
type: Opaque
data:
  redisURL: {{ .Values.redisURL | b64enc | quote }}
  postgresURL: {{ .Values.postgresURL | b64enc | quote }}
  minioEndpoint: {{ .Values.minioEndpoint | b64enc | quote }}
  workerKey: {{ .Values.workerKey | b64enc | quote }}
