kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
# Hack: force NodePort to be 33333 until envoy-gateway supports specifying the service nodePort
- |
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      "service-node-port-range": "33333-33333"
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 33333
    hostPort: 3333
    protocol: TCP